Add missing Dutch translations, align with en resource file
OpenVPN/openvpn-gui pull request #358
Opened 2020-08-27 10:04 UTC by EagleErwin

This PR adds three missing Dutch translations (`IDS_NFO_IMPORT_OVERWRITE`, `IDS_ERR_IMPORT_SOURCE` and `IDS_NFO_BYTECOUNT` and modifies the text in the `ID_DLG_ABOUT` dialog to match the English source text.

I have also aligned the order of the lines in the file and some whitespace with the `openvpn-gui-res-en.rc` file to make file comparison easier.

2020-09-04 11:48 UTC, lstipakov requested changes
A few nitpicks, rest looks good.

2020-09-04 11:48 UTC, lstipakov commented on res/openvpn-gui-res-nl.rc
> +    LTEXT "OpenVPN - Een programma om veilig IP-netwerken te tunnellen " \
should be `tunnelen`

2020-09-04 11:48 UTC, lstipakov commented on res/openvpn-gui-res-nl.rc
> +                             "Kies een nieuw wachtwoord."
First line should be `Het nieuwe wachtwoord bevat niet-toegestane tekens.` - "The new password contains disallowed characters", not "The new password does not contain allowed characters".

2020-09-05 13:13 UTC, EagleErwin commented on res/openvpn-gui-res-nl.rc
> +    LTEXT "OpenVPN - Een programma om veilig IP-netwerken te tunnellen " \
Nice catch!

2020-09-05 13:14 UTC, EagleErwin commented
Fixed the review comments and rebased on the current master to fix merge conflict.

2020-09-07 06:46 UTC, lstipakov approved these changes
Looks good, according to native Dutch speaker.

2020-09-07 15:18 UTC, merged